# Generated by Django 6.1.1 on 2026-10-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
